// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL7qHkm3FSuN2peyKeB2_S_hClQKsVk-o',
    appId: '1:634925148106:web:32b6d0bda61a3f449c9133',
    messagingSenderId: '634925148106',
    projectId: 'newapp-86348',
    authDomain: 'newapp-86348.firebaseapp.com',
    storageBucket: 'newapp-86348.firebasestorage.app',
    measurementId: 'G-CYYNMR7GT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhPl89RI3P3Xn_ejpf34sk5HIL6SKVxfw',
    appId: '1:634925148106:android:d3013b3e3ad8f2229c9133',
    messagingSenderId: '634925148106',
    projectId: 'newapp-86348',
    storageBucket: 'newapp-86348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYiM6d-fRy7FcBLMiH2Ls0g2Kafo1E6bI',
    appId: '1:634925148106:ios:07c8af50d35aa0629c9133',
    messagingSenderId: '634925148106',
    projectId: 'newapp-86348',
    storageBucket: 'newapp-86348.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYiM6d-fRy7FcBLMiH2Ls0g2Kafo1E6bI',
    appId: '1:634925148106:ios:07c8af50d35aa0629c9133',
    messagingSenderId: '634925148106',
    projectId: 'newapp-86348',
    storageBucket: 'newapp-86348.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC21BGt74T3jBovd1KvqQMroOi_N4SOi8w',
    appId: '1:634925148106:web:c3da81dd5fb073ad9c9133',
    messagingSenderId: '634925148106',
    projectId: 'newapp-86348',
    authDomain: 'newapp-86348.firebaseapp.com',
    storageBucket: 'newapp-86348.firebasestorage.app',
    measurementId: 'G-V288PHH2EQ',
  );
}
